# General settings 
app:
  name: "House Price Prediction"
  version: "1.0.0"
  environment: "development" 

# Data settings
data:
  raw_data_path: "housing.csv"
  test_size: 0.3
  random_state: 42

# Model settings
model1:
  name: "Standard Scaler"
  type: StandardScaler
model2:
  name: "Linear Regression"
  type: LinearRegression

# Evaluation settings
evaluation:
  metrics:
    - "r2_score"